<a href="https://colab.research.google.com/github/marcelodepaoli/02_Numpy/blob/main/1_NumPy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NumPy
O NumPy é uma biblioteca de Álgebra Linear para Python. A razão de sua importância vem do fato que praticamente todas as bibliotecas do ecossistema PyData dependem do NumPy.
Além disso, ele é incrivelmente rápido, pois tem conexões com bibliotecas do C.

#Instruções de instação
É altamente recomendado que você instale o Python utilizando a distribuição Anaconda. Isso garante que todas as dependências internas fiquem sincronizadas. Se você tem o Anaconda, para instalar o NumPy abra o terminal ou prompt de comano=fo e digite:

`conda install numpy`

#Utilizando o NumPy
Após intalar você pode importá-lo como uma biblioteca

In [ ]:
import numpy as np

#NumPy Arrays
Numpy arrays aparecem essencialmente em duas formas: vetores e matrizes. Vetores são estritamemente arrays 1-d e matrizes são 2-d (porém, uma matriz pode, eventualmente, conter apenas uma coluna ou uma linha).

#Criando NumPy Arrays

####De uma lista
Pode-se criar uma array convertendo diretamente uma lista ou lista de listas

In [ ]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [ ]:
np.array(my_list)

array([1, 2, 3])

In [ ]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#Métodos de Construção Interna
Existem vários métodos internos para gerar arrays

####arange
Retorna valores separados igualmente em um dado intervalo

In [ ]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

####zeros e ones
Gera arrays de zeros e uns

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

####linspace
Retorna números uniformemente espaçados em um intervalo específico

In [ ]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

####eye
Cria uma matrix identidade

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#Random
O numpy possui várias formas de criar arrays de números aleatórios

#### rand
Cria uma array na forma dada e popula ela com amostras aleatórias de uma distribuição uniforme entre [0,1)

In [ ]:
np.random.rand(2)

array([0.48827293, 0.9481016 ])

In [ ]:
np.random.rand(5,5)

array([[0.77511842, 0.0254753 , 0.55039402, 0.19047372, 0.95858454],
       [0.78656975, 0.15244434, 0.36242808, 0.95838644, 0.15114475],
       [0.34632215, 0.95145085, 0.69083056, 0.8635782 , 0.92745155],
       [0.477497  , 0.79350051, 0.06217877, 0.56256226, 0.84862922],
       [0.23953607, 0.55110982, 0.06223048, 0.82433384, 0.77291991]])

####randn
Retorna uma amostra (ou amostras) de uma "distribuição normal padrão". Diferente do rand, que é uniforme

In [ ]:
np.random.randn(2)

array([-0.74603454,  0.69417488])

In [ ]:
np.random.randn(5,5)

array([[-0.71520916,  0.73357826,  1.29586275, -0.49804876,  1.2775569 ],
       [-1.67691737, -2.06781291, -0.58598824, -0.9689648 , -0.34604956],
       [-1.87190459, -1.68632572,  0.14929125,  0.6497332 , -2.27137001],
       [ 0.59439564, -0.80045377,  1.43892273,  2.36832095,  0.71244968],
       [-0.0837616 , -0.80785591, -0.64380785,  1.43067291,  0.93238905]])

####randint
Retorna um inteiro aleatório entre low (inclusive) e high (exclusivo)

In [ ]:
np.random.randint(1,100)

56

In [ ]:
np.random.randint(1,100,200)

array([86, 27,  8, 48, 79, 33, 25, 95, 30, 82, 59, 74, 80, 57, 65, 39, 19,
       55, 29, 14, 92, 61, 95, 87, 85, 50, 14, 92, 58, 28, 82, 66, 30, 47,
       14, 81, 70, 23, 49, 33, 38,  2, 72, 93, 32, 71, 62, 89, 19, 94, 15,
       10, 51, 94, 84, 22, 29, 50, 46, 14, 55, 17, 40, 37, 82, 14, 57, 94,
       12,  6, 16, 29, 67, 80, 66, 38, 73, 94, 59,  2, 39, 24, 80, 73, 41,
       53, 68, 73, 49, 79, 71, 48, 82, 12, 82, 26, 60, 78,  2, 30, 34, 21,
       86, 38, 49, 70, 60, 13, 58, 94, 13, 43, 37, 96, 70, 25, 63, 16,  1,
       98, 78,  1, 69, 79, 87, 94, 21, 79,  1, 57, 40, 20, 44, 22, 15, 98,
       14, 40, 35, 75, 79, 30, 40, 71, 23, 42, 95, 84, 55, 75, 83, 27, 30,
       57, 49, 62, 90, 85, 74, 42, 45, 69, 94, 54, 36, 48, 49, 20, 59, 75,
       91, 12, 44, 95, 41, 88, 99, 86,  2, 46,  1, 91, 38, 33, 91, 98, 22,
       92, 15, 90, 51, 17,  7, 41, 30, 42, 55, 54, 85, 18])

#Atributos e Métodos das Arrays
Vamos discutir alguns atributos e métodos úteis de uma array 

In [ ]:
arr = np.arange(25)

In [ ]:
ranarr = np.random.randint(0,50,10)

In [ ]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr

array([41, 22, 44,  0,  8, 15, 12, 39, 41, 35])

####Reshape
Retorna uma array contendo a mesma informação com uma nova forma

In [ ]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

####max, min, argmax, argmin
Estes são métodos úteis para encontrar valores máximos ou mínimos. Ou para encontrar seu índice de localização utilizando argmin ou argmax

In [ ]:
ranarr

array([41, 22, 44,  0,  8, 15, 12, 39, 41, 35])

In [ ]:
ranarr.max()

44

In [ ]:
ranarr.argmax()

2

In [ ]:
ranarr.min()

0

In [ ]:
ranarr.argmin()

3

####Shape
Shape é um atributo que as arrays possuem (não é um método)

In [ ]:
#vetor
arr.shape

(25,)

In [ ]:
#perceba os 2 pares de colchetes
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
arr.reshape(1,25).shape

(1, 25)

In [ ]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [ ]:
arr.reshape(25,1).shape

(25, 1)

####dtype
Também é possível obter o tipo de dado dos objetos de uma array

In [ ]:
arr.dtype

dtype('int64')